### ISSUE TITLE
Expose HTTP API to return latest rates

### ISSUE THREAD

**Issue by D4nte** [coblox/bobtimus#46]
Bobtimus should expose a HTTP API to return the latest rates.

A proposal of the JSON payload is present in https://github.com/coblox/makeshift/pull/2

You would need to use the `TestnetMarketMaker.getAmountsToPublish()` method to access some of the information to publish.

**Comment by D4nte** [comment]
Something that was not explicitly said is how do we intend to publish the link.

To me, we do a Apache or nginx configuration that serves the HTML file containing the link and does the redirect.

**Comment by bonomat** [comment]
> To me, we do a Apache or nginx configuration that serves the HTML file containing the link and does the redirect.

Way simpler. Bobtimus is written in node, so why not just this expressjs: 
https://expressjs.com/en/starter/hello-world.html 

```
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => res.send('comit+web....'))

app.listen(port, () => console.log(`Bobtimus listening on port ${port}!`))
```

**Comment by D4nte** [comment]
Let's have a quick chat at Monday's grooming.

**Comment by bonomat** [comment]
> expressJS
yap: 

```
app.get("/latestrate", (req, res) => {
    res.status(301).redirect("https://www.google.com")
})
```

**Comment by D4nte** [comment]
Proposed addition: Show a Bitcoin and Ether address at `http://<bobtimus_ip/` to allow people to fund Bobtimus if a balance is too low.

**Comment by bonomat** [comment]
> Proposed addition: Show a Bitcoin and Ether address at http://<bobtimus_ip/ to allow people to fund Bobtimus if a balance is too low.

I would not reveal that Bobtimus is running low, that could just motivate people to misuse poor Bob. Instead, I would just statically say: `Please donate some testnet BTC to bc1... and robsten ETH to 0x1337`

**Comment by bonomat** [comment]
Let's block this for now and discuss if and how we still want to do it.

**Comment by D4nte** [comment]
> Let's block this for now and discuss if and how we want to do it.

When are we going to discuss it?

**Comment by da-kami** [comment]
The express client will be created in the `index.js` - there we have the `TradeEvaluationService` - but it currently only exposes `isTradeAcceptable`. `calculateAmountsToPublish` is currently only implemented in `TestnetMarketMaker`.

Assumption: 
`TradeEvaluationService` should contain `calculateAmountsToPublish`, because it should not matter which rate-strategy is used, bobtimus should always be able to publish the rate if requested. 

Proposal:
* Rename `TradeEvaluationService` to `TradeService`
* add `calculateAmountsToPublish` to `TradeService`
* Always expose the API (`express` object to be created at the end of the main async function which handles the `shoot`)
* The API has exactly one endpoint `bobtimus_url/rates` which returns the rates for all configured ledger-asset combinations of bobtimus (response as defined in `makeshift`).

@bonomat @D4nte please let me know if that matches with your thoughts :)
